services:
  - postgres

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  before_script:
    - ./gradlew --stop
    - fuser -k 8080/tcp
  script:
    - ./gradlew build -x test

job2:
  stage: test
  script:
    - ./gradlew build

job3:
  stage: deploy
  script:
    - sudo ./deployShell.sh &

