services:
  - postgres

stages:
  - build & test
  - deploy

job1:
  stage: build
  script:
    - ./gradlew build -x test

job2:
  stage: test
  script:
    - ./gradlew build

after_script:
  - ./gradlew --stop
  - ./gradlew bootRun


