/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebAppServer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void thisTestPassesAnyWay() {
        assertTrue(true);
    }
//    @Test public void canGetCorrectData(){
//        User user = ToDatabase.getUser(0);
//        System.out.println(user.getUsername());
//        assertTrue(user.getUsername().equals("{admin}"));
//    }
}
